//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acacia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acacia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for account &apos;{0}&apos; is not available. Advanced Z-Push features will not work..
        /// </summary>
        internal static string AccountNoPassword_Body {
            get {
                return ResourceManager.GetString("AccountNoPassword_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password unavailable.
        /// </summary>
        internal static string AccountNoPassword_Title {
            get {
                return ResourceManager.GetString("AccountNoPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Feature_DebugSupport {
            get {
                return ResourceManager.GetString("Feature_DebugSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free/Busy.
        /// </summary>
        internal static string Feature_FreeBusy {
            get {
                return ResourceManager.GetString("Feature_FreeBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Address Book.
        /// </summary>
        internal static string Feature_GAB {
            get {
                return ResourceManager.GetString("Feature_GAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Feature_Notes {
            get {
                return ResourceManager.GetString("Feature_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of office.
        /// </summary>
        internal static string Feature_OutOfOffice {
            get {
                return ResourceManager.GetString("Feature_OutOfOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply flags.
        /// </summary>
        internal static string Feature_ReplyFlags {
            get {
                return ResourceManager.GetString("Feature_ReplyFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures.
        /// </summary>
        internal static string Feature_Signatures {
            get {
                return ResourceManager.GetString("Feature_Signatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Book for {0}.
        /// </summary>
        internal static string GAB_FolderFormat {
            get {
                return ResourceManager.GetString("GAB_FolderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifications to the Global Address Book are not allowed. Please contact your administrator if you think changes are required..
        /// </summary>
        internal static string GABEvent_Body {
            get {
                return ResourceManager.GetString("GABEvent_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Address Book.
        /// </summary>
        internal static string GABEvent_Title {
            get {
                return ResourceManager.GetString("GABEvent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Kopano {
            get {
                object obj = ResourceManager.GetObject("Kopano", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopano Folders.
        /// </summary>
        internal static string LocalStore_DisplayName {
            get {
                return ResourceManager.GetString("LocalStore_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve Out of Office settings. You can still enable or disable Out of Office, but applying the settings might fail..
        /// </summary>
        internal static string OOFGet_Failed {
            get {
                return ResourceManager.GetString("OOFGet_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving current Out of Office settings.
        /// </summary>
        internal static string OOFGet_Label {
            get {
                return ResourceManager.GetString("OOFGet_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Office Assistant.
        /// </summary>
        internal static string OOFGet_Title {
            get {
                return ResourceManager.GetString("OOFGet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of office has been enabled, but the server could not handle your full request.
        ///
        ///.
        /// </summary>
        internal static string OOFSet_DifferentState {
            get {
                return ResourceManager.GetString("OOFSet_DifferentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Office has been disabled..
        /// </summary>
        internal static string OOFSet_Disabled {
            get {
                return ResourceManager.GetString("OOFSet_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to disable Out of Office..
        /// </summary>
        internal static string OOFSet_DisableFailed {
            get {
                return ResourceManager.GetString("OOFSet_DisableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Office has been enabled until further notice..
        /// </summary>
        internal static string OOFSet_Enabled {
            get {
                return ResourceManager.GetString("OOFSet_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Office has been enabled from {0} till {1}..
        /// </summary>
        internal static string OOFSet_EnabledTimeBased {
            get {
                return ResourceManager.GetString("OOFSet_EnabledTimeBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to enable Out of Office..
        /// </summary>
        internal static string OOFSet_EnableFailed {
            get {
                return ResourceManager.GetString("OOFSet_EnableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply Out of Office settings.
        /// </summary>
        internal static string OOFSet_Failed {
            get {
                return ResourceManager.GetString("OOFSet_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying Out of Office settings.
        /// </summary>
        internal static string OOFSet_Label {
            get {
                return ResourceManager.GetString("OOFSet_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Office Assistant.
        /// </summary>
        internal static string OOFSet_Title {
            get {
                return ResourceManager.GetString("OOFSet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Office is currently enabled on account &apos;{0}&apos;. Would you like to change the settings?.
        /// </summary>
        internal static string OOFStartup_Message {
            get {
                return ResourceManager.GetString("OOFStartup_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Office Assistant.
        /// </summary>
        internal static string OOFStartup_Title {
            get {
                return ResourceManager.GetString("OOFStartup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_About {
            get {
                object obj = ResourceManager.GetObject("Ribbon_About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Ribbon_About_Label {
            get {
                return ResourceManager.GetString("Ribbon_About_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About dialog.
        /// </summary>
        internal static string Ribbon_About_Screentip {
            get {
                return ResourceManager.GetString("Ribbon_About_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_About_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_About_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the about dialog, which contains licensing and version information..
        /// </summary>
        internal static string Ribbon_About_Supertip {
            get {
                return ResourceManager.GetString("Ribbon_About_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_AddSharedFolder {
            get {
                object obj = ResourceManager.GetObject("Ribbon_AddSharedFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_AddSharedFolder_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_AddSharedFolder_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_Debug {
            get {
                object obj = ResourceManager.GetObject("Ribbon_Debug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Ribbon_Debug_Label {
            get {
                return ResourceManager.GetString("Ribbon_Debug_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug dialog.
        /// </summary>
        internal static string Ribbon_Debug_Screentip {
            get {
                return ResourceManager.GetString("Ribbon_Debug_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_Debug_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_Debug_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the debug dialog, which shows information on the Kopano Outlook Extension..
        /// </summary>
        internal static string Ribbon_Debug_Supertip {
            get {
                return ResourceManager.GetString("Ribbon_Debug_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopano.
        /// </summary>
        internal static string Ribbon_GroupMain_Label {
            get {
                return ResourceManager.GetString("Ribbon_GroupMain_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_Logfile {
            get {
                object obj = ResourceManager.GetObject("Ribbon_Logfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_Logfile_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_Logfile_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_ManageSharedFolders {
            get {
                object obj = ResourceManager.GetObject("Ribbon_ManageSharedFolders", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_ManageSharedFolders_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_ManageSharedFolders_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_MDM {
            get {
                object obj = ResourceManager.GetObject("Ribbon_MDM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_MDM_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_MDM_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_OOF {
            get {
                object obj = ResourceManager.GetObject("Ribbon_OOF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out-of-Office.
        /// </summary>
        internal static string Ribbon_OOF_Label {
            get {
                return ResourceManager.GetString("Ribbon_OOF_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Out-of-Office settings.
        /// </summary>
        internal static string Ribbon_OOF_Screentip {
            get {
                return ResourceManager.GetString("Ribbon_OOF_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_OOF_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_OOF_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a dialog which allows Out-of-Office settings to be viewed or modified..
        /// </summary>
        internal static string Ribbon_OOF_Supertip {
            get {
                return ResourceManager.GetString("Ribbon_OOF_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_Restore {
            get {
                object obj = ResourceManager.GetObject("Ribbon_Restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_Restore_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_Restore_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_Rules {
            get {
                object obj = ResourceManager.GetObject("Ribbon_Rules", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_Rules_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_Rules_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_Settings {
            get {
                object obj = ResourceManager.GetObject("Ribbon_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Ribbon_Settings_Label {
            get {
                return ResourceManager.GetString("Ribbon_Settings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings dialog.
        /// </summary>
        internal static string Ribbon_Settings_Screentip {
            get {
                return ResourceManager.GetString("Ribbon_Settings_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_Settings_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_Settings_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the settings dialog, which allows configuration of the plugin and access to support functions..
        /// </summary>
        internal static string Ribbon_Settings_Supertip {
            get {
                return ResourceManager.GetString("Ribbon_Settings_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_SharedFolders {
            get {
                object obj = ResourceManager.GetObject("Ribbon_SharedFolders", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_SharedFolders_Context {
            get {
                object obj = ResourceManager.GetObject("Ribbon_SharedFolders_Context", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage shared folder.
        /// </summary>
        internal static string Ribbon_SharedFolders_Context_Label {
            get {
                return ResourceManager.GetString("Ribbon_SharedFolders_Context_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage this folder in the Shared Folders dialog.
        /// </summary>
        internal static string Ribbon_SharedFolders_Context_Screentip {
            get {
                return ResourceManager.GetString("Ribbon_SharedFolders_Context_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the &quot;Shared Folders&quot; dialog for the currently selected folder..
        /// </summary>
        internal static string Ribbon_SharedFolders_Context_Supertip {
            get {
                return ResourceManager.GetString("Ribbon_SharedFolders_Context_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared folders.
        /// </summary>
        internal static string Ribbon_SharedFolders_Label {
            get {
                return ResourceManager.GetString("Ribbon_SharedFolders_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage shared folders.
        /// </summary>
        internal static string Ribbon_SharedFolders_Screentip {
            get {
                return ResourceManager.GetString("Ribbon_SharedFolders_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_SharedFolders_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_SharedFolders_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the &quot;Shared Folders&quot; dialog, which can be used to add or remove shared folders..
        /// </summary>
        internal static string Ribbon_SharedFolders_Supertip {
            get {
                return ResourceManager.GetString("Ribbon_SharedFolders_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_SyncGAB {
            get {
                object obj = ResourceManager.GetObject("Ribbon_SyncGAB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_SyncGAB_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_SyncGAB_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopano.
        /// </summary>
        internal static string Ribbon_Title {
            get {
                return ResourceManager.GetString("Ribbon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_WebApp {
            get {
                object obj = ResourceManager.GetObject("Ribbon_WebApp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open WebApp.
        /// </summary>
        internal static string Ribbon_WebApp_Label {
            get {
                return ResourceManager.GetString("Ribbon_WebApp_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open WebApp.
        /// </summary>
        internal static string Ribbon_WebApp_Screentip {
            get {
                return ResourceManager.GetString("Ribbon_WebApp_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_WebApp_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_WebApp_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open WebApp in the system default browser.
        /// </summary>
        internal static string Ribbon_WebApp_Supertip {
            get {
                return ResourceManager.GetString("Ribbon_WebApp_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_WebMeetings {
            get {
                object obj = ResourceManager.GetObject("Ribbon_WebMeetings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ribbon_WebMeetings_Small {
            get {
                object obj = ResourceManager.GetObject("Ribbon_WebMeetings_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contacts folder &apos;{0}&apos; has been discovered. It is being synchronised, but will not show up in the list of contacts folders until Outlook is restarted. Click &apos;Yes&apos; to restart Outlook now, or &apos;No&apos; if you plan to restart Outlook later..
        /// </summary>
        internal static string SecondaryContactsPatched_Body {
            get {
                return ResourceManager.GetString("SecondaryContactsPatched_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts folder.
        /// </summary>
        internal static string SecondaryContactsPatched_Title {
            get {
                return ResourceManager.GetString("SecondaryContactsPatched_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the shared folder. Please ensure you have permission to open the shared folder..
        /// </summary>
        internal static string SharedFolders_Adding_Failure {
            get {
                return ResourceManager.GetString("SharedFolders_Adding_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening shared folder.
        /// </summary>
        internal static string SharedFolders_Adding_Label {
            get {
                return ResourceManager.GetString("SharedFolders_Adding_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared folders.
        /// </summary>
        internal static string SharedFolders_Adding_Title {
            get {
                return ResourceManager.GetString("SharedFolders_Adding_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply the changes to the shared folders. Please try again later..
        /// </summary>
        internal static string SharedFolders_Applying_Failure {
            get {
                return ResourceManager.GetString("SharedFolders_Applying_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying changes to shared folders.
        /// </summary>
        internal static string SharedFolders_Applying_Label {
            get {
                return ResourceManager.GetString("SharedFolders_Applying_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes to the shared folders have been applied successfully..
        /// </summary>
        internal static string SharedFolders_Applying_Success {
            get {
                return ResourceManager.GetString("SharedFolders_Applying_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared folders.
        /// </summary>
        internal static string SharedFolders_Applying_Title {
            get {
                return ResourceManager.GetString("SharedFolders_Applying_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close shared folder {0}?.
        /// </summary>
        internal static string SharedFolders_Closing_Confirm {
            get {
                return ResourceManager.GetString("SharedFolders_Closing_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close the shared folder..
        /// </summary>
        internal static string SharedFolders_Closing_Failure {
            get {
                return ResourceManager.GetString("SharedFolders_Closing_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing shared folder.
        /// </summary>
        internal static string SharedFolders_Closing_Label {
            get {
                return ResourceManager.GetString("SharedFolders_Closing_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared folders.
        /// </summary>
        internal static string SharedFolders_Closing_Title {
            get {
                return ResourceManager.GetString("SharedFolders_Closing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve shared folders. Please try again later..
        /// </summary>
        internal static string SharedFolders_Fetching_Failure {
            get {
                return ResourceManager.GetString("SharedFolders_Fetching_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving shared folders.
        /// </summary>
        internal static string SharedFolders_Fetching_Label {
            get {
                return ResourceManager.GetString("SharedFolders_Fetching_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared folders.
        /// </summary>
        internal static string SharedFolders_Fetching_Title {
            get {
                return ResourceManager.GetString("SharedFolders_Fetching_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving shared folders.
        /// </summary>
        internal static string SharedFolders_Loading {
            get {
                return ResourceManager.GetString("SharedFolders_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving shared folders.
        /// </summary>
        internal static string SharedFolders_Loading_Error {
            get {
                return ResourceManager.GetString("SharedFolders_Loading_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shared folders are available.
        /// </summary>
        internal static string SharedFolders_None {
            get {
                return ResourceManager.GetString("SharedFolders_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SharedFolders_Permission_None {
            get {
                return ResourceManager.GetString("SharedFolders_Permission_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string SharedFolders_Permission_Read {
            get {
                return ResourceManager.GetString("SharedFolders_Permission_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string SharedFolders_Permission_Write {
            get {
                return ResourceManager.GetString("SharedFolders_Permission_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public folders.
        /// </summary>
        internal static string SharedFolders_PublicFolders {
            get {
                return ResourceManager.GetString("SharedFolders_PublicFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes. Do you really want to to discard these?.
        /// </summary>
        internal static string SharedFolders_Unsaved_Changes {
            get {
                return ResourceManager.GetString("SharedFolders_Unsaved_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signatures are being synchronised..
        /// </summary>
        internal static string SignaturesSync_Label {
            get {
                return ResourceManager.GetString("SignaturesSync_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures.
        /// </summary>
        internal static string SignaturesSync_Title {
            get {
                return ResourceManager.GetString("SignaturesSync_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error with the security certificate for server {0}. Do you want to allow the connection anyway?.
        /// </summary>
        internal static string SSLFailed_Body {
            get {
                return ResourceManager.GetString("SSLFailed_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate error.
        /// </summary>
        internal static string SSLFailed_Title {
            get {
                return ResourceManager.GetString("SSLFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopano.
        /// </summary>
        internal static string ThisAddIn_Title {
            get {
                return ResourceManager.GetString("ThisAddIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeLoading {
            get {
                object obj = ResourceManager.GetObject("TreeLoading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
